name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Clear existing files
        run: |
          rm -f ./syllabus.json
          rm -f ./app.db

      - name: Verify files were removed
        run: |
          if [ -f "./syllabus.json" ]; then
            echo "Failed to remove syllabus.json"
            exit 1
          fi
          if [ -f "./app.db" ]; then
            echo "Failed to remove app.db"
            exit 1
          fi
          echo "Files successfully removed"

      - name: Build JSON and SQLite DB
        run: bun run build

      - name: Check if files were created
        run: |
          if [ ! -f "./syllabus.json" ]; then
            echo "syllabus.json was not created"
            exit 1
          fi
          if [ ! -f "./app.db" ]; then
            echo "app.db was not created"
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            ./syllabus.json
            ./app.db
